extends: ["spectral:oas"]
rules:
  operation-operationId: error
  operation-tags: error
  operation-description: off
  info-contact: off
  # CouchDB uses `_`-prefixed paths like /_all_dbs
  path-keys-no-trailing-slash: error
